### PR TITLE
espressif: adjustments after IDF v5.1 compatibility, secure boot build and memory map organization

### PR DESCRIPTION
**Pull request by almir-okato**
This PR makes some adjustments on Security Chain building overall, remove unsupported configurations from ESP32-C2 `bootloader.conf` and also organizes and document the memory organization describing the address ranges that the OS must avoid.

### CODE REVIEW

**Comment by almir-okato** [comment]
@sylvioalves @marekmatej @utzig PTAL

**Review by utzig — APPROVED** [review]

**Comment by sylvioalves** [comment]
@nordicjm This might fix that CI issue presented at #1774.

**Review by d3zd3z — CHANGES_REQUESTED** [review]
Can you add a release note stub (probably just as an additional commit). See [submitting patches](https://github.com/mcu-tools/mcuboot/blob/main/docs/SubmittingPatches.md) release notes section for specifics.

**Comment by almir-okato** [comment]
> Can you add a release note stub (probably just as an additional commit). See [submitting patches](https://github.com/mcu-tools/mcuboot/blob/main/docs/SubmittingPatches.md) release notes section for specifics.

Ah this is nice. Thanks!
I added a commit for that.

**Review by sylvioalves — APPROVED** [review]

**Review by d3zd3z — APPROVED** [review]

**Comment by d3zd3z** [comment]
Merging despite the mynewt failure, as that will get fixed by another PR.

**Pull request merged**
