### PR TITLE
Update version files for 2.0.0

### PR DESCRIPTION
**Pull request by d3zd3z**
Update documentation and version tags for final 2.0.0 release.

### CODE REVIEW

**Review by nordicjm — COMMENTED** [review]
The title is wrong, no changes in PR relate to zephyr (or changes for zephyr are missing from this PR)

**Comment by d3zd3z** [comment]
I seem to have Zephyr-on-the-brain. I'll fix this.

**Comment by d3zd3z** [comment]
@nordicjm I've fixed the stray Zephyr. We won't think too deeply about the commit already there that incorrectly mentions Zephyr.

**Review by thedjnK — CHANGES_REQUESTED** [review]
Missing update of https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/VERSION

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by d3zd3z** [comment]
I'd like to pull in the mynewt version upgrade. It was unclear to me if this is supposed to happen before or after the actual release. But, shouldn't the mynewt version also be 2.0.0?

**Pull request merged**
