### PR TITLE
boot: zephyr: Add a custom boot banner

### PR DESCRIPTION
**Pull request by erwango**
Cutomize MCUBoot boot banner to ease identifiation of boot steps in console.

### CODE REVIEW

**Review by nordicjm — CHANGES_REQUESTED** [review]
The problem with this is it does not print the MCUboot version, it prints the zephyr version

**Comment by erwango** [comment]
> The problem with this is it does not print the MCUboot version, it prints the zephyr version

Agreed. This was a quick attempt, printing the right version would require additional change in Zephyr. I need to find some time to address it.

**Comment by nordicjm** [comment]
> > The problem with this is it does not print the MCUboot version, it prints the zephyr version
> 
> Agreed. This was a quick attempt, printing the right version would require additional change in Zephyr. I need to find some time to address it.

It should be able to be done in MCUboot itself as ncs does it

**Comment by nordicjm** [comment]
Closing as superseded by https://github.com/mcu-tools/mcuboot/pull/1945

**Pull request closed without merging**
