### PR TITLE
boot: zephyr: add nrf52840 QSPI NOR overlays

### PR DESCRIPTION
**Pull request by utzig**
Add configuration and DTS overlays to run MCUboot + smp_svr on the nrf52840dk using the secondary slot in the external QSPI NOR flash.

### CODE REVIEW

**Comment by utzig** [comment]
Maybe this should be inside Zephyr, but since it's not working 100% I am leaving it here as a draft...

Building the `MCUboot`:

```
west build -b nrf52840dk_nrf52840 zephyr/samples/subsys/mgmt/mcumgr/smp_svr -- -DDTC_OVERLAY_FILE=$(pwd)/bootloader/mcuboot/boot/zephyr/nrf52840dk_spi_secondary.overlay -DOVERLAY_CONFIG="overlay-bt.conf;$(pwd)/bootloader/mcuboot/boot/zephyr/nrf52840dk_spi_secondary_app.conf"
west flash -d build_boot
```

Building `smp_svr`:

```
west build -b nrf52840dk_nrf52840 zephyr/samples/subsys/mgmt/mcumgr/smp_svr -- -DDTC_OVERLAY_FILE=$(pwd)/bootloader/mcuboot/boot/zephyr/nrf52840dk_spi_secondary.overlay -DOVERLAY_CONFIG="overlay-bt.conf;$(pwd)/bootloader/mcuboot/boot/zephyr/nrf52840dk_spi_secondary.conf"
west sign -t imgtool -- --key bootloader/mcuboot/root-rsa-2048.pem -v 1.0.0
west flash --hex-file build/zephyr/zephyr.signed.hex
```

Currently I can use mcumgr to upload new images with:

```
sudo mcumgr --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' image upload build/zephyr/zephyr.signed.bin
```

But `image test` and `image confirm` don't work. Nothing happens. If I build an image with `--pad` and load manually to the QSPI NOR flash with `nrfjprog` it does run an upgrade test and does revert properly, so I assume the issue is with mcumgr on Zephyr (for now!). Btw, also tried passing in `--align 8` just to be sure and the results are the same.

/cc @mbolivar-nordic

**Comment by utzig** [comment]
Turns out I was missing `CONFIG_NORDIC_QSPI_NOR_STACK_WRITE_BUFFER_SIZE`. The `nrf_qspi_nor.c` returns `-EINVAL` in this case, but somewhere up the chain it is being ignored. Now all upgrade operations work correctly.

**Review by mbolivar-nordic — APPROVED** [review]
Looks good to me. Any additional changes needed to make it work using partition manager within NCS?

**Comment by nvlsianpu** [comment]
> Looks good to me. Any additional changes needed to make it work using partition manager within NCS?

Only patch to PM's *.yaml is needed (in NCS repo).

**Review by nvlsianpu — COMMENTED** [review]
I think it is worth to add https://github.com/mcu-tools/mcuboot/blob/master/boot/zephyr/sample.yaml sample description:

``` yaml
  sample.bootloader.mcuboot.qspi_nor_slot:
    extra_args: DTC_OVERLAY_FILE=./nrf52840dk_spi_secondary.overlay
      OVERLAY_CONFIG="./nrf52840dk_spi_secondary.conf;./nrf52840dk_spi_secondary_boot.conf"
    platform_allow:  nrf52840dk_nrf52840
    tags: bootloader_mcuboot
```

Also fille you added are a board specific, so maybe move it into boards directory,

**Review by nvlsianpu — APPROVED** [review]

**Comment by mbolivar-nordic** [comment]
> Only patch to PM's *.yaml is needed (in NCS repo).

Will someone be doing this too then?

**Pull request merged**
