### PR TITLE
ci: mynewt: Sync with upstream Github Actions

### PR DESCRIPTION
**Pull request by sjanc**
Build Mynewt targets in similar way as Mynewt GH Actions. This also enables running Mynewt specific tests.

### CODE REVIEW

**Comment by utzig** [comment]
Test reason those `xxx_install.sh` and `xxx_run.sh` scripts exist is that we used to run tests on Travis as well, so GH workflows and Travis could share the install/run steps. Who knows if in the future there won't be need to migrate to something else. I think you could just as easily have updated them.

**Comment by sjanc** [comment]
well, I was looking at zephyr integration but I'm fine with just updating those scripts, will update PR tomorrow

**Comment by utzig** [comment]
> well, I was looking at zephyr integration but I'm fine with just updating those scripts, will update PR tomorrow

Yep, I didn't remember those, but Zephyr has unlimited resources and can change everything tomorrow if needed.

**Comment by utzig** [comment]
Rebase!

**Review by utzig — APPROVED** [review]
LGTM

**Pull request merged**
