### PR TITLE
Pointless change

### PR DESCRIPTION
**Pull request by d3zd3z**
Not to be merged, merely to provoke CI on 'main'.

### CODE REVIEW

**Comment by nordicjm** [comment]
@kasjer would you be able to have a look at the mynewt failure which seems to be due to recent changes with mbedtls in mynewt itself?

**Comment by kasjer** [comment]
@sjanc maybe CI script should download mbedtls same way nrfx handled?

**Comment by sjanc** [comment]
There is PR pending (from May...) which is handling this
https://github.com/mcu-tools/mcuboot/pull/1706

**Comment by almir-okato** [comment]
Regarding the failure on Espressif workflow, currently I made some changes related to the memory map: https://github.com/mcu-tools/mcuboot/pull/1779
It should pass the CI.

**Comment by d3zd3z** [comment]
Issues resolved.

**Pull request closed without merging**
