### PR TITLE
imgtool: Fix getpriv error return with private key

### LINKED ISSUE #1746: imgtool getpriv does not work on enc-ec256-priv.pem file
Seemingly the following commit has broken imgtool support for getting private keys, at least with the `enc-ec256-priv.pem` which is included with mcuboot using the following command `./scripts/imgtool.py getpriv -k enc-ec256-priv.pem`:
```
commit 5704174c126f8757e09588f9b9133f4ad0f6a0c6
Author: Roland Mikhel <roland.mikhel@arm.com>
Date:   Fri Feb 3 14:43:13 2023 +0100

    imgtool: Add generic ECDSA TLV support
    
    Update imgtool to support the new
    generic ECDSA TLV and the ECDSA
    p384 curve type with sha-384
    
    Signed-off-by: Roland Mikhel <roland.mikhel@arm.com>
    Change-Id: I9b1887610cc5d0e7cde90f47999fcdf3500ef51c
```
Output with this change:
```
Usage: imgtool.py getpriv [OPTIONS]
Try 'imgtool.py getpriv -h' for help.

Error: Operation get_private_bytes requires private key
```
Output from previous commit:
```
/* Autogenerated by imgtool.py, do not edit. */
const unsigned char enc_priv_key[] = {
    0x30, 0x81, 0x87, 0x02, 0x01, 0x00, 0x30, 0x13,
    0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
    0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d,
    0x03, 0x01, 0x07, 0x04, 0x6d, 0x30, 0x6b, 0x02,
    0x01, 0x01, 0x04, 0x20, 0xf6, 0x1e, 0x51, 0x9d,
    0xf8, 0xfa, 0xdd, 0xa1, 0xb7, 0xd9, 0xa9, 0x64,
    0x64, 0x3b, 0x54, 0xd0, 0x3d, 0xd0, 0x1f, 0xe5,
    0x78, 0xd9, 0x17, 0x98, 0xa5, 0x28, 0xca, 0xcc,
    0x6b, 0x67, 0x9e, 0x06, 0xa1, 0x44, 0x03, 0x42,
    0x00, 0x04, 0x8a, 0x44, 0x73, 0x00, 0x94, 0xc9,
    0x80, 0x27, 0x31, 0x0d, 0x23, 0x36, 0x6b, 0xe9,
    0x69, 0x9f, 0xcb, 0xc5, 0x7c, 0xc8, 0x44, 0x1a,
    0x93, 0xe6, 0xee, 0x7d, 0x86, 0xa6, 0xae, 0x5e,
    0x93, 0x72, 0x74, 0xd9, 0xe1, 0x5a, 0x1c, 0x9b,
    0x65, 0x1a, 0x2b, 0x61, 0x41, 0x28, 0x02, 0x73,
    0x84, 0x12, 0x97, 0x3a, 0x2d, 0xa2, 0xa0, 0x67,
    0x77, 0x02, 0xda, 0x67, 0x1a, 0x4b, 0xdd, 0xd7,
    0x71, 0xcc,
};
const unsigned int enc_priv_key_len = 138;
```
And what makes this most annoying is that the version value is completely invalid, from current `main`:
```
./scripts/imgtool.py version
1.10.0
```
From my system imgtool (where I *can* get the private key of this key successfully):
```
imgtool version
1.10.0
```

### PR DESCRIPTION
**Pull request by Roolli**
Fixes #1746

### CODE REVIEW

**Review by davidvincze — APPROVED** [review]

**Comment by davidvincze** [comment]
@nordicjm may I ask you to review @Roolli's fix? Thank you.

**Review by nordicjm — CHANGES_REQUESTED** [review]
Not working.
Old:
```
imgtool getpub -k enc-ec256-pub.pem 
/* Autogenerated by imgtool.py, do not edit. */
const unsigned char ecdsa_pub_key[] = {
    0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86,
    0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a,
    0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
    0x42, 0x00, 0x04, 0x8a, 0x44, 0x73, 0x00, 0x94,
    0xc9, 0x80, 0x27, 0x31, 0x0d, 0x23, 0x36, 0x6b,
    0xe9, 0x69, 0x9f, 0xcb, 0xc5, 0x7c, 0xc8, 0x44,
    0x1a, 0x93, 0xe6, 0xee, 0x7d, 0x86, 0xa6, 0xae,
    0x5e, 0x93, 0x72, 0x74, 0xd9, 0xe1, 0x5a, 0x1c,
    0x9b, 0x65, 0x1a, 0x2b, 0x61, 0x41, 0x28, 0x02,
    0x73, 0x84, 0x12, 0x97, 0x3a, 0x2d, 0xa2, 0xa0,
    0x67, 0x77, 0x02, 0xda, 0x67, 0x1a, 0x4b, 0xdd,
    0xd7, 0x71, 0xcc,
};
const unsigned int ecdsa_pub_key_len = 91;
```
With this:
```
python ./scripts/imgtool.py getpub -k enc-ec256-pub.pem > 2
Traceback (most recent call last):
  File "/tmp/qq/mcuboot/./scripts/imgtool.py", line 22, in <module>
    main.imgtool()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/qq/mcuboot/scripts/imgtool/main.py", line 144, in getpub
    key.emit_c_public()
  File "/tmp/qq/mcuboot/scripts/imgtool/keys/general.py", line 28, in emit_c_public
    encoded_bytes=self.get_public_bytes(),
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/qq/mcuboot/scripts/imgtool/keys/ecdsa.py", line 37, in get_public_bytes
    return self._get_public().public_bytes(
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/qq/mcuboot/scripts/imgtool/keys/ecdsa.py", line 33, in _get_public
    return self.key.public_key()
           ^^^^^^^^^^^^^^^^^^^
AttributeError: '_EllipticCurvePublicKey' object has no attribute 'public_key'. Did you mean: 'public_bytes'?
```

**Comment by davidvincze** [comment]
> Not working. Old:
> 
> ```
> imgtool getpub -k enc-ec256-pub.pem 
> /* Autogenerated by imgtool.py, do not edit. */
> const unsigned char ecdsa_pub_key[] = {
>     0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86,
>     0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a,
>     0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
>     0x42, 0x00, 0x04, 0x8a, 0x44, 0x73, 0x00, 0x94,
>     0xc9, 0x80, 0x27, 0x31, 0x0d, 0x23, 0x36, 0x6b,
>     0xe9, 0x69, 0x9f, 0xcb, 0xc5, 0x7c, 0xc8, 0x44,
>     0x1a, 0x93, 0xe6, 0xee, 0x7d, 0x86, 0xa6, 0xae,
>     0x5e, 0x93, 0x72, 0x74, 0xd9, 0xe1, 0x5a, 0x1c,
>     0x9b, 0x65, 0x1a, 0x2b, 0x61, 0x41, 0x28, 0x02,
>     0x73, 0x84, 0x12, 0x97, 0x3a, 0x2d, 0xa2, 0xa0,
>     0x67, 0x77, 0x02, 0xda, 0x67, 0x1a, 0x4b, 0xdd,
>     0xd7, 0x71, 0xcc,
> };
> const unsigned int ecdsa_pub_key_len = 91;
> ```
> 
> With this:
> 
> ```
> python ./scripts/imgtool.py getpub -k enc-ec256-pub.pem > 2
> Traceback (most recent call last):
>   File "/tmp/qq/mcuboot/./scripts/imgtool.py", line 22, in <module>
>     main.imgtool()
>   File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/tmp/qq/mcuboot/scripts/imgtool/main.py", line 144, in getpub
>     key.emit_c_public()
>   File "/tmp/qq/mcuboot/scripts/imgtool/keys/general.py", line 28, in emit_c_public
>     encoded_bytes=self.get_public_bytes(),
>                   ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/tmp/qq/mcuboot/scripts/imgtool/keys/ecdsa.py", line 37, in get_public_bytes
>     return self._get_public().public_bytes(
>            ^^^^^^^^^^^^^^^^^^
>   File "/tmp/qq/mcuboot/scripts/imgtool/keys/ecdsa.py", line 33, in _get_public
>     return self.key.public_key()
>            ^^^^^^^^^^^^^^^^^^^
> AttributeError: '_EllipticCurvePublicKey' object has no attribute 'public_key'. Did you mean: 'public_bytes'?
> ```

I haven't tested it with the enc-* keys, only the ones that are used for signing, sorry. @Roolli could you have a look at it, please?

**Review by davidvincze — CHANGES_REQUESTED** [review]
Please fix the issue with public key objects.

**Review by davidvincze — APPROVED** [review]
Thank you for the fix.

**Review by nordicjm — APPROVED** [review]

**Pull request merged**
