### PR TITLE
Preps for 2.1.0 release

### PR DESCRIPTION
**Pull request by d3zd3z**
Update version information for 2.1.0 release.

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by davidvincze** [comment]
Could you please update README.md:21 as well? From `This is MCUboot version 2.1.0-rc1` to `This is MCUboot version 2.1.0`.

**Comment by de-nordic** [comment]
> Could you please update README.md:21 as well? From `This is MCUboot version 2.1.0-rc1` to `This is MCUboot version 2.1.0`.

DNM till the comment is resolved.

**Review by davidvincze — APPROVED** [review]
Thank you!

**Review by nordicjm — APPROVED** [review]

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
We discovered something which might be a bug while building for one of signature algorithm.
Need to grab details and try to reproduce and confirm if true.

**Review by de-nordic — APPROVED** [review]

**Comment by d3zd3z** [comment]
@de-nordic are we ok to remove DNM?

**Pull request merged**
