### PR TITLE
imgtool: option to read key passphrase from environment

### PR DESCRIPTION
**Pull request by crazyscot**
In a CI chain it is sometimes useful to automatically sign an image (e.g. once qualification tests have passed). Naturally, it is important to protect the private key in such cases.

This patch provides that capability.

The private key should be stored in a passphrase-protected PEM file in the usual way. The CI provider should be configured, through its secrets mechanism, to inject the passphrase as an environment variable of your choice. A new imgtool option is then used to specify that variable name, e.g.:
   imgtool --password-env=DEV_KEY_PASSPHRASE sign infile.hex outfile.hex

This option also works for the other verbs that load keys (getpub, getpriv, imgfile).

Note that argument ordering is critical. --password-env must appear before the verb!

### CODE REVIEW

**Comment by utzig** [comment]
@crazyscot The commit needs to be signed.

**Comment by crazyscot** [comment]
> @crazyscot The commit needs to be signed.

Done, thanks.

**Comment by crazyscot** [comment]
My apologies, it appears that I messed up pushing the GPG signature on this. Commit updated, can we remove the stale label please?

**Review by de-nordic — APPROVED** [review]

**Comment by d3zd3z** [comment]
> My apologies, it appears that I messed up pushing the GPG signature on this. Commit updated, can we remove the stale label please?

Oh, I think what @utzig meant to say was the the commit needs a sign-off-by footer in the commit text. There is not a requirement to sign commits in this project.

**Review by d3zd3z — APPROVED** [review]

**Pull request closed without merging**
