### PR TITLE
boot: zephyr: add support for generic watchdog alias

### PR DESCRIPTION
**Pull request by bbilas**
Add possibility to pass generic watchdog alias no matter what vendor is used.

Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>

### CODE REVIEW

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
For nRF devices CONFIG_NRFX_WDT=y & CONFIG_BOOT_WATCHDOG_FEED=y are always assured.
MCUBOOT_WATCHDOG_FEED() variant for CONFIG_NRFX_WDT=y must take precedence before the generic one - otherwise it will be impossible to be enabled.

**Comment by bbilas** [comment]
> For nRF devices CONFIG_NRFX_WDT=y & CONFIG_BOOT_WATCHDOG_FEED=y are always assured. MCUBOOT_WATCHDOG_FEED() variant for CONFIG_NRFX_WDT=y must take precedence before the generic one - otherwise it will be impossible to be enabled.

I've moved the watchdog alias as the last choice.

**Comment by bbilas** [comment]
@nvlsianpu do you have any idea where that increase comes from?

**Comment by nvlsianpu** [comment]
@bbilas ^^ issue was fixed on main branch recently.

**Comment by bbilas** [comment]
Rebased with main.

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
