### PR TITLE
zephyr: Wrapped the RAM loading mode in Zephyr configs.

### PR DESCRIPTION
**Pull request by johan-ohman**
The RAM loading mode wasn't wrapped in Zephyr configs like the other boot modes.
Added a config to enable RAM loading as well as two configs to set
IMAGE_EXECUTABLE_RAM_START and IMAGE_EXECUTABLE_RAM_SIZE, respectively. These
two values default to the values from the chosen node sram in the dts.

Signed-off-by: Johan Öhman <johan.ohman@softube.com>

### CODE REVIEW

**Comment by johan-ohman** [comment]
> Can a testcase for check whether this built be added to the sample.yaml?

I don't have any experience with the sample.yaml file and it's not obvious to me what I'm meant to add to it. Could you please point me in the right direction?

**Comment by nvlsianpu** [comment]
ok ^^ will show how to do that

**Comment by johan-ohman** [comment]
Hello again @nvlsianpu!
I added a commit with a test case. Could you please take a look and tell me if it looks good?

**Comment by johan-ohman** [comment]
Aha! What a silly mistake. I fixed this and squashed it all into one commit. Let's hope it passes the tests this time!

**Review by d3zd3z — APPROVED** [review]

**Comment by johan-ohman** [comment]
Ping @nvlsianpu

**Comment by nvlsianpu** [comment]
@johan-ohman I assumes you are able to chainload the application using that. Do you?

**Review by nvlsianpu — COMMENTED** [review]
might went in as initial support

**Pull request merged**
