### PR TITLE
boot: Add the support of MBEDTLS version 3.0.0

### PR DESCRIPTION
**Pull request by Sherryzhang2**
Signed-off-by: Sherry Zhang <sherry.zhang2@arm.com>
Change-Id: Idd7ce989fe259e9003732e80beaf3dccdedd3050

### CODE REVIEW

**Review by tamasban — COMMENTED** [review]
If I got this right this should not be merged?  It was just used to verify the backward compatibility with the previous mbedTLs version. If this is right then please close this PR.

**Comment by Sherryzhang2** [comment]
> If I got this right this should not be merged? It was just used to verify the backward compatibility with the previous mbedTLs version. If this is right then please close this PR.

Yes, you are right. Will close it.

**Comment by Sherryzhang2** [comment]
This PR is just for the backward compatibility test.

**Comment by Sherryzhang2** [comment]
TEST PASSED. Closed the PR.

**Pull request closed without merging**
