### PR TITLE
boot_serial: zephyr: allow to build when CONFIG_MULTITHREADING=n

### PR DESCRIPTION
**Pull request by nvlsianpu**
K_sleep() is not available when multithreading is disabled.
Let's use k_busy_wait() in that case.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @nordic-krch

**Review by utzig — APPROVED** [review]

**Review by nordic-krch — APPROVED** [review]

**Comment by de-nordic** [comment]
Can you help me with building this?
I do:
```
 west build -b nrf52840dk_nrf52840 -d voot bootloader/mcuboot/boot/zephyr/ -p -- -DCONFIG_MCUBOOT_SERIAL=y -DCONFIG_UART_CONSOLE=n
```

And get:
```
...
zephyrproject-clean/voot/zephyr/include/generated/syscalls/kernel.h:86: undefined reference to `z_impl_k_sleep'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```


This is my top in mcuboot: 9f4358853362671d5278b676235f433b4b2dc1a0 , zephyr  41e885947e4f48aae0866df9e5fee657afb7c1cc

**Comment by nordic-krch** [comment]
`k_sleep` is used in `main.c` as well.

**Review by de-nordic — APPROVED** [review]
Looks OK.

I have been able to build and test the change on nrf52840dk, works fine.

Thanks!

**Pull request merged**
