### PR TITLE
Revert RAM load single application commits

### PR DESCRIPTION
**Pull request by nordicjm**
These commits should not have been merged until after the zephyr 4.0 stablilisation process was complete, a bug has been found which needs to be included in MCUboot for this release, therefore revert the commits so an MCUboot module update can be included

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]

**Comment by teburd** [comment]
Which bug needs to be included out of curousity?

**Comment by carlescufi** [comment]
Next time, why not create a `v4.0.0` branch in sdk-mcuboot so that we can cherry-pick fixes there but continue to use main?

**Comment by de-nordic** [comment]
> Next time, why not create a `v4.0.0` branch in sdk-mcuboot so that we can cherry-pick fixes there but continue to use main?

I think that MCUboot requires some definition of release management and proper branching for that.
Not only for sdk-mcuboot but for upstream too.

**Comment by nordicjm** [comment]
The PR was merged by someone that does not follow zephyr releases so was not aware of the zephyr release, it should not have been merged during the zephyr release time. And I'm not fond of creating mirror branches which then deviate from how we use mcuboot in main, for an lts release that's fine or if there is a security fix needed in a still supported version of zephyr but having multiple branches for no reason creates a mess

**Comment by carlescufi** [comment]
@nordicjm but MCUboot is its own project, I am not sure why the release cadence and cycles of Zephyr, which is one of its users, should influence the state of `main` in MCUboot.

**Comment by nordicjm** [comment]
> @nordicjm but MCUboot is its own project, I am not sure why the release cadence and cycles of Zephyr, which is one of its users, should influence the state of `main` in MCUboot.

It is it's own project, the 2 active developers/maintainers are zephyr developers, so the overlap is almost 100%

**Pull request merged**
