### PR TITLE
ESP32: Basic MCUBoot support

### PR DESCRIPTION
**Pull request by shubhamkulkarni97**
* Added `boot/espressif` directory which includes MCUboot port, loader implementation and HAL files.
* ESP-IDF is added as a submodule for including HAL files in build.
* This port is tested with Zephyr based applications.

### Setting up the environment

* `git submodule update --init --recursive` (Update ESP-IDF submodule)
* `unset IDF_PATH` (Clear IDF_PATH variable if it is already set)
* `./boot/espressif/hal/esp-idf/install.sh` (Installs toolchain required to build application for ESP32)
* `. ./boot/espressif/hal/esp-idf/export.sh` (Adds required directories to PATH)

### Steps to build and flash MCUBoot port for ESP32

* cd boot/espressif
* cmake -DCMAKE_TOOLCHAIN_FILE=tools/toolchain-esp32.cmake -DMCUBOOT_TARGET=esp32 -DIDF_PATH=$IDF_PATH -B build -GNinja
* cd build && ninja
* export ESPPORT=your-esp32-serial-port
* $IDF_PATH/components/esptool_py/esptool/esptool.py --chip esp32 elf2image --flash_mode dio --flash_freq 40m -o mcuboot_esp32.bin mcuboot_esp32.elf
* $IDF_PATH/components/esptool_py/esptool/esptool.py -p $ESPPORT -b 2000000 --before default_reset --after hard_reset --chip esp32 write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 mcuboot_esp32.bin

### Steps to flash Host application (Hello-World application binary attached below):

* $IDF_PATH/components/esptool_py/esptool/esptool.py -p $ESPPORT -b 2000000 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x10000 app.bin

Zephyr hello_world application binary: [app.bin.zip](https://github.com/mcu-tools/mcuboot/files/6695380/app.bin.zip)

**NOTE:** Upstream Zephyr port for ESP32 doesn't support MCUBoot, it needs changes which are still under internal review

### CODE REVIEW

**Comment by shubhamkulkarni97** [comment]
@d3zd3z Could you please take a look? Thanks.

**Review by d3zd3z — CHANGES_REQUESTED** [review]
I'm ok with the changes themselves. I have not reviewed in too much depth, as the changes are localized to the target directory.

My only change request is to add a prefix to the commit summary lines so it is clear what these changes are in regards to. Perhaps "espressif: ", or "esp32: ".

**Comment by shubhamkulkarni97** [comment]
Thanks for the review, I will update this PR with required changes.

**Review by d3zd3z — APPROVED** [review]

**Comment by shubhamkulkarni97** [comment]
Added minor changes

**Comment by shubhamkulkarni97** [comment]
@d3zd3z Can we merge this PR if it looks good?

**Review by d3zd3z — APPROVED** [review]

**Pull request merged**
