### PR TITLE
imgtool: enhance password support

### PR DESCRIPTION
**Pull request by kurddt**
Allow to pass the private key password as an option by either
providing directly using pass:<password> or via environment using
env:<variable_name>

### CODE REVIEW

**Comment by utzig** [comment]
I don't think this is OK. There **are** reasons why passwords should not exist in the open, so if you really want it for everyone to see, why even use a password?

Btw, if you REALLY want to give a password as an environment variable or plain text, just use `sshpass` (https://linux.die.net/man/1/sshpass):

```
sshpass -p <your-plaintext-password> -P "Enter key passphrase:" imgtool create <parameters>
```

or `-e` to get the password from `$SSHPASS`. This should be enough to deal with your issue.

**Comment by kurddt** [comment]
Hi thanks for your comments, the sshpass won't work in my use case. I want to sign a zephyr application during CI and I don't think it's possible to insert a command before the imgtool invocation during the build process. I could remove the plain text option and only use the environment variable possibility

**Comment by utzig** [comment]
> Hi thanks for your comments, the sshpass won't work in my use case. I want to sign a zephyr application during CI and I don't think it's possible to insert a command before the imgtool invocation during the build process. I could remove the plain text option and only use the environment variable possibility

An example of using `sshpass` in a CI can be seen here: https://github.com/nrfconnect/sdk-nrf/blob/master/.github/workflows/docpublish.yml#L48. It's getting the password from the environment variable with `-e` which is what you want, so if you have access to the CI you can do it.

**Comment by utzig** [comment]
> I could remove the plain text option and only use the environment variable possibility

That would be less bad for sure.

**Comment by d3zd3z** [comment]
Probably some relationship to #599 here, which may or may not help with this particular case. Using something like a software hsm could allow an hsm-aware imgtool to not need to prompt for passwords.

**Pull request closed without merging**
