### PR TITLE
Proposed 1.7.2

### PR DESCRIPTION
**Pull request by d3zd3z**
Proposed changes for a v1.7.2 release.

### CODE REVIEW

**Review by utzig — CHANGES_REQUESTED** [review]
Need to update `imgtool` release.

**Comment by tamasban** [comment]
Thanks for starting the release preparation, the content looks okay. In 010665d David's signed-of-by line is missing, this cause CI failure.

**Review by nvlsianpu — COMMENTED** [review]
Scope looks OK.

**Comment by utzig** [comment]
@tamasban @RcColes seems to me like one of TFM's dependencies is causing a Travis failure again: https://travis-ci.org/github/d3zd3z/mcuboot/jobs/760621151#L2513

**Comment by tamasban** [comment]
@utzig @d3zd3z:  These also need to be cherry-picked to fix the build issue with TF-M:

713bb79 ci: Update TF-M version
f684738 ci: Pin tf-m-tests version in FIH test
7cca88a ci: Update tf-m version in FIH test

**Comment by tamasban** [comment]
I have checked the CI.  It failed because this version of TF-M, assumes to have the a mcuboot/boot/bootutil/CMakeList.txt: 
7ad5c5f23f4619add4aa6c88f4b25fc6fd84ec6e

Please remove the commit 5a0af83 from this PR. Asa result TF-M will be reverted to an earlier version(8501b37), which does not rely on the CMakeList.txt in MCUboot.  I have tested it local it seems okay.

**Comment by d3zd3z** [comment]
@tamasban:

> Please remove the commit 5a0af83 from this PR. Asa result TF-M will be reverted to an earlier version(8501b37), which does not rely on the CMakeList.txt in MCUboot. I have tested it local it seems okay.

Were you able to just remove this patch? 18a88ba25ca changes the version used, but the patch being removed removes the hard coding of the version entirely.

**Review by utzig — APPROVED** [review]
LGTM

**Review by tamasban — APPROVED** [review]
The content looks okay. Thanks!

**Comment by Sherryzhang2** [comment]
The content looks good to me.

**Review by nvlsianpu — APPROVED** [review]

**Pull request merged**
