### PR TITLE
Mbed-OS: Prevent use of BlockDevice with unreliable erase value

### PR DESCRIPTION
**Pull request by AGlass0fMilk**
The default return value of `BlockDevice::get_erase_value` is -1. When implicitly cast from an `int` to a `uint8_t`, this gets truncated to `0xFF`, which is normally a reasonable erase value.

However, the intent of the Mbed-OS BlockDevice API is that an **integer** value of -1 is to be interpreted as an "unreliable" erase value. ie: the underlying BlockDevice does not have a known erase value.

If a user attempts to use such a BlockDevice (eg: SDBlockDevice at the moment, see ARMmbed/mbed-os#15070), they may encounter hard to debug errors.

Since MCUboot expects some fields to be the "erased value" under certain boot/swap states, a BlockDevice with an unreliable erase value is not compatible with MCUboot. It is recommended that the user wrap the incompatible BlockDevice in a [`FlashSimBlockDevice`](https://github.com/ARMmbed/mbed-os/blob/64a34193b126aed25497021b7617f9dadf7ae7a8/storage/blockdevice/include/blockdevice/FlashSimBlockDevice.h) to provide a known erase value.

This commit adds an assert that will (hopefully) catch such an error during development.

Signed-off-by: George Beckstein <george.beckstein@gmail.com>

### CODE REVIEW

**Comment by AGlass0fMilk** [comment]
@LDong-Arm @boraozgen

**Comment by AGlass0fMilk** [comment]
Updated the comments to recommend use of the [`FlashSimBlockDevice`](https://github.com/ARMmbed/mbed-os/blob/64a34193b126aed25497021b7617f9dadf7ae7a8/storage/blockdevice/include/blockdevice/FlashSimBlockDevice.h) to ensure a known erase value and enable compatibility with MCUboot.

See ARMmbed/mbed-os#15071

**Review by d3zd3z — CHANGES_REQUESTED** [review]
The change looks fine to me. Do you mind wrapping the lines, though, in the commit text, so that they don't exceed about 75 columns.

**Comment by d3zd3z** [comment]
The failed mynewt test should pass after re-pushing. The certificate issue has been resolved. Rebasing will bring in a change that ignores the certificate, though.

**Comment by d3zd3z** [comment]
Is there still interest in getting this merged?

**Comment by AGlass0fMilk** [comment]
Unfortunately I no longer contribute to Mbed-OS, so someone else will have to push this along.

**Pull request closed without merging**
