### PR TITLE
docs: espressif: fix formatting of markdown

### PR DESCRIPTION
**Pull request by utzig**
Fix documentation issues for the rendering of the Espressif README page. No content is changed with this commit, but formatting and line breaks are set to approximately 100 columns.

### CODE REVIEW

**Comment by utzig** [comment]
Supersedes #1789, tested locally...

**Review by almir-okato — APPROVED** [review]
LGTM

Thanks @utzig, I tried to test it locally but couldn't build properly using Ruby Gems (tried with and without GitHub Pages Docker image), would be possible to add the instructions somewhere in the project?

**Comment by utzig** [comment]
> LGTM
> 
> Thanks @utzig, I tried to test it locally but couldn't build properly using Ruby Gems (tried with and without GitHub Pages Docker image), would be possible to add the instructions somewhere in the project?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

^ Is this missing something?

I submitted PR #1798 which adds emoji support, missing here https://docs.mcuboot.com/readme-espressif.html#building-bootloader-with-flash-encryption. Also adds `webrick` required for ruby > 3.

I tested locally with ruby 3.0.6 (shipped with my distro) and 2.7.4 (used by github pages) which I manage with `rbenv`. `rubygems` comes with disto as well; install the required bundler with: `gem install bundler -v 1.17.2`, and run `bundle install`. I never use docker for ruby/python stuff...

**Comment by almir-okato** [comment]
> > LGTM
> > Thanks @utzig, I tried to test it locally but couldn't build properly using Ruby Gems (tried with and without GitHub Pages Docker image), would be possible to add the instructions somewhere in the project?
> 
> https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
> 
> ^ Is this missing something?
> 
> I submitted PR #1798 which adds emoji support, missing here https://docs.mcuboot.com/readme-espressif.html#building-bootloader-with-flash-encryption. Also adds `webrick` required for ruby > 3.
> 
> I tested locally with ruby 3.0.6 (shipped with my distro) and 2.7.4 (used by github pages) which I manage with `rbenv`. `rubygems` comes with disto as well; install the required bundler with: `gem install bundler -v 1.17.2`, and run `bundle install`. I never use docker for ruby/python stuff...

Yes I tried to build using those instructions from docs.github.com. 
But with the updates from your PR https://github.com/mcu-tools/mcuboot/pull/1798, it worked fine, so I guess the problem was probably related to plugins version from Gemfile.

**Pull request merged**
