### PR TITLE
sim: Calculate offsets from boot_max_align instead of hardcoding them

### PR DESCRIPTION
**Pull request by gustavonihei**
This PR intends to prepare the simulator to execute images with a max align value other than 8 bytes.

**Note**: change extracted from patch series proposed on PR https://github.com/mcu-tools/mcuboot/pull/1217

### CODE REVIEW

**Comment by utzig** [comment]
There was another bit of code which also was not related to changing the alignments that could also be here...

**Comment by utzig** [comment]
> There was another bit of code which also was not related to changing the alignments that could also be here...

`mark_permanent_upgrade`

**Comment by gustavonihei** [comment]
> There was another bit of code which also was not related to changing the alignments that could also be here...

True, I've updated the PR. Thanks for the heads up!

**Review by utzig — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
